package cjava.view;

import cjava.controller.ProductoBLL;
import cjava.entity.ProductoTO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class productostodoView extends javax.swing.JInternalFrame {

  public productostodoView() {
    initComponents();
    listaProductos();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    tblProducto = new javax.swing.JTable();
    btnCerrar = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    lblTotal = new javax.swing.JLabel();

    setTitle("LISTA DE PRODUCTOS");

    tblProducto.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Codigo", "Nombre", "Categoria", "Precio", "Stock"
      }
    ));
    jScrollPane1.setViewportView(tblProducto);
    if (tblProducto.getColumnModel().getColumnCount() > 0) {
      tblProducto.getColumnModel().getColumn(0).setPreferredWidth(50);
      tblProducto.getColumnModel().getColumn(1).setPreferredWidth(200);
      tblProducto.getColumnModel().getColumn(2).setPreferredWidth(60);
      tblProducto.getColumnModel().getColumn(3).setPreferredWidth(50);
      tblProducto.getColumnModel().getColumn(4).setPreferredWidth(50);
    }

    btnCerrar.setText("Cerrar");
    btnCerrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCerrarActionPerformed(evt);
      }
    });

    jLabel1.setText("Total de Productos");

    lblTotal.setText("0");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGap(31, 31, 31)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnCerrar)
          .addComponent(jLabel1)
          .addComponent(lblTotal))
        .addContainerGap(24, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

 private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
   this.dispose();
 }//GEN-LAST:event_btnCerrarActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCerrar;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lblTotal;
  private javax.swing.JTable tblProducto;
  // End of variables declaration//GEN-END:variables
   // instanciar objerto de la clase ProductoBLL
  ProductoBLL obj = new ProductoBLL();

  private void listaProductos() {
    try {
      List<ProductoTO> lista = obj.ProductoListar();
      lblTotal.setText(lista.size() + "");
      verProductos(lista);
    } catch (Exception e) {
    }
  }

  private void verProductos(List<ProductoTO> lista) {
    // variabvle de tipo tabla
    DefaultTableModel tabla = (DefaultTableModel) tblProducto.getModel();
    tabla.setRowCount(0);
    for (ProductoTO x : lista) {
      Object[] pro = {x.getIdproducto(), x.getDescripcion(), x.getIdcategoria(), x.getPrecioventa(), x.getStock()};
      tabla.addRow(pro);//adiciona al control tabla
    }
  }

}
