package cjava.view;

import cjava.controller.CategoriaBLL;
import cjava.controller.ProductoBLL;
import cjava.entity.CategoriaTO;
import cjava.entity.ProductoTO;
import javax.swing.JOptionPane;

public class productomanview extends javax.swing.JInternalFrame {

  public productomanview() {
    initComponents();
    try {
      cargaCombo();
    } catch (Exception e) {
    }

  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    txtcodigo = new javax.swing.JTextField();
    txtnombre = new javax.swing.JTextField();
    cboCategoria = new javax.swing.JComboBox();
    txtprecompra = new javax.swing.JTextField();
    txtpreventa = new javax.swing.JTextField();
    txtcantidad = new javax.swing.JTextField();
    btnAdicionar = new javax.swing.JButton();
    btnModificar = new javax.swing.JButton();
    btnEliminar = new javax.swing.JButton();
    btnBuscar = new javax.swing.JButton();
    btnCerrar = new javax.swing.JButton();

    setTitle("MANTENIMIENTO DE PRODUCTO");

    jLabel1.setText("Codigo");

    jLabel2.setText("Nombre de Producto");

    jLabel3.setText("Categoria");

    jLabel4.setText("Precio Compra");

    jLabel5.setText("Precio Venta");

    jLabel6.setText("Cantidad");

    btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cjava/imagen/save_all.png"))); // NOI18N
    btnAdicionar.setText("Adicionar");
    btnAdicionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnAdicionar.setMaximumSize(new java.awt.Dimension(75, 49));
    btnAdicionar.setMinimumSize(new java.awt.Dimension(75, 49));
    btnAdicionar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAdicionarActionPerformed(evt);
      }
    });

    btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cjava/imagen/contact-list.png"))); // NOI18N
    btnModificar.setText("Modificar");
    btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnModificar.setMaximumSize(new java.awt.Dimension(75, 49));
    btnModificar.setMinimumSize(new java.awt.Dimension(75, 49));
    btnModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    btnModificar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnModificarActionPerformed(evt);
      }
    });

    btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cjava/imagen/Cancel.png"))); // NOI18N
    btnEliminar.setText("Eliminar");
    btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnEliminar.setMaximumSize(new java.awt.Dimension(77, 51));
    btnEliminar.setMinimumSize(new java.awt.Dimension(77, 51));
    btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    btnEliminar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEliminarActionPerformed(evt);
      }
    });

    btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cjava/imagen/buscar.gif"))); // NOI18N
    btnBuscar.setText("Buscar");
    btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnBuscar.setMaximumSize(new java.awt.Dimension(77, 51));
    btnBuscar.setMinimumSize(new java.awt.Dimension(77, 51));
    btnBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    btnBuscar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBuscarActionPerformed(evt);
      }
    });

    btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cjava/imagen/application-exit.png"))); // NOI18N
    btnCerrar.setText("Cerrar");
    btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    btnCerrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCerrarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(37, 37, 37)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(txtprecompra, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(txtpreventa, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel6)))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(txtcodigo)
                    .addGap(18, 18, 18))
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel1)
                    .addGap(81, 81, 81)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel2)
                  .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(47, 47, 47))))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(25, 25, 25)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(jLabel2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(24, 24, 24)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(jLabel4)
          .addComponent(jLabel5)
          .addComponent(jLabel6))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtprecompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtpreventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(btnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(1, 1, 1))
          .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
          .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(29, 29, 29))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

 private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
   this.dispose();
 }//GEN-LAST:event_btnCerrarActionPerformed

 private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
   procesar(1);
 }//GEN-LAST:event_btnAdicionarActionPerformed

 private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
   procesar(2);
 }//GEN-LAST:event_btnModificarActionPerformed

 private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
   procesar(3);
 }//GEN-LAST:event_btnEliminarActionPerformed

 private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
   try {
    mostrarDatos(); 
   } catch (Exception e) {
   }
   
 }//GEN-LAST:event_btnBuscarActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAdicionar;
  private javax.swing.JButton btnBuscar;
  private javax.swing.JButton btnCerrar;
  private javax.swing.JButton btnEliminar;
  private javax.swing.JButton btnModificar;
  private javax.swing.JComboBox cboCategoria;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JTextField txtcantidad;
  private javax.swing.JTextField txtcodigo;
  private javax.swing.JTextField txtnombre;
  private javax.swing.JTextField txtprecompra;
  private javax.swing.JTextField txtpreventa;
  // End of variables declaration//GEN-END:variables
  CategoriaBLL ocat = new CategoriaBLL();

  private void cargaCombo() throws Exception {
    cboCategoria.removeAllItems();
    for (CategoriaTO c : ocat.CategoriaListar()) {
      cboCategoria.addItem(c);
    }
  }
  // instanciar objeto de la clase ProductoBLL
  ProductoBLL obj = new ProductoBLL();
  ProductoTO pr;

  private void procesar(int op) {
    int sw;
    String msg = null;
    leerDatos();
    try {
      switch (op) {
        case 1:
          sw = obj.ProductoAdicionar(pr);
          txtcodigo.setText(pr.getIdproducto());
          msg = "Producto registrado con exito";
          break;
        case 2:
          pr.setIdproducto(txtcodigo.getText());
          sw = obj.ProductoActualizar(pr);
          msg = "Producto actualizado con exito";
          break;
        case 3:
          pr.setIdproducto(txtcodigo.getText());
          sw = obj.ProductoEliminar(pr);
          msg = "Producto eliminado con exito";
          break;       
      }
      JOptionPane.showMessageDialog(this, msg);
    } catch (Exception e) {
      JOptionPane.showMessageDialog(this, e.getMessage());
    }

  }

  private void leerDatos() {
    pr = new ProductoTO();
    //pr.setIdproducto(txtcodigo.getText());
    pr.setDescripcion(txtnombre.getText());
    pr.setIdcategoria(cboCategoria.getSelectedIndex() + 1);
    pr.setPreciocompra(Double.parseDouble(txtprecompra.getText()));
    pr.setPrecioventa(Double.parseDouble(txtpreventa.getText()));
    pr.setStock(Integer.parseInt(txtcantidad.getText()));
  }

  private void mostrarDatos() throws Exception {
    pr = obj.ProductoBuscar(txtcodigo.getText());
    if (pr != null) {
      txtnombre.setText(pr.getDescripcion());
      txtprecompra.setText(pr.getPreciocompra() + "");
      txtpreventa.setText(pr.getPrecioventa() + "");
      txtcantidad.setText(pr.getStock() + "");
      cboCategoria.setSelectedIndex(pr.getIdcategoria() - 1);
    } else {
      JOptionPane.showMessageDialog(this, "Producto no existe");
    }
  }

}
